apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: blogs/cronjob:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: runcronjob
                  value: "true"
          restartPolicy: Never
